### ISSUE TITLE
IBM Cloud tests failing at cncf.ci due to infrastructure account config issues for the VLANs

### ISSUE THREAD

**Issue by kitch** [crosscloudci/crosscloudci#77]
### Specified VLAN not found during provisioning

Example of failure: 
https://gitlab.cncf.ci/cncf/cross-cloud/-/jobs/111842

```
for it to be tainted.
data.ibm_network_vlan.vlan_private: Refreshing state...
data.ibm_org.orgdata: Refreshing state...
data.ibm_network_vlan.vlan_public: Refreshing state...
data.ibm_account.accountData: Refreshing state...

Error: Error refreshing state: 2 error(s) occurred:

* data.ibm_network_vlan.vlan_public: 1 error(s) occurred:

* data.ibm_network_vlan.vlan_public: data.ibm_network_vlan.vlan_public: No VLAN was found with the name 'public'
* data.ibm_network_vlan.vlan_private: 1 error(s) occurred:

* data.ibm_network_vlan.vlan_private: data.ibm_network_vlan.vlan_private: No VLAN was found with the name 'private'
```

This is caused because the terraform is referring to vlans that do not exist.
https://github.com/crosscloudci/cross-cloud/blob/master/ibm/bluemix.tf#L29

It's not clear to me where the actual VLAN IDs are being specified in the CI process. We would need to find the owner of the IBM Cloud account in order to find the proper VLANs to be used in this process.

**Comment by taylor** [comment]
@albee-jhoney @ IBM commented:

In the context of the account used to run this job, I have the following question:
* Was the public & private vlan created with names "public" and "private" (and it is case-sensitive) ? Did anyone recently change the names of the public & private vlan ?
* The account owner, must login to Softlayer UI, to verify the public & private vlan status ?
Or use this API -- https://api.softlayer.com/rest/v3/SoftLayer_Account/getNetworkVlans.json? to query & get all vlans in their account (using SL username & apikey).

We were able to use the same terraform template (blueprint.tf & modified inputs.tf) with our account - it worked.
Hence, the issue is not in terraform..

When we provided the wrong vlan names in the terraform config file, we got the same error messages


Error: Error refreshing state: 2 error(s) occurred:

* data.ibm_network_vlan.vlan_public: 1 error(s) occurred:
* data.ibm_network_vlan.vlan_public: data.ibm_network_vlan.vlan_public: No VLAN was found with the name 'testvlan_public'

* data.ibm_network_vlan.vlan_private: 1 error(s) occurred:
* data.ibm_network_vlan.vlan_private: data.ibm_network_vlan.vlan_private: No VLAN was found with the name 'testvlan_private'

**Comment by taylor** [comment]
@albee-jhoney and @kitch:

The VLAN IDs are determined by name through the IBM API by Terraform.  The names are specified in the [bluemix.tf template](https://github.com/crosscloudci/cross-cloud/blob/master/ibm/bluemix.tf#L16) as "public" and "private".

After logging into the Softlayer UI (via IBM ID auth), we see no VLANs listed on the page https://control.softlayer.com/network/vlans.  (FYI, the IBM ID auth does not give access to the API link provided).

From what we can see, we do not have the ability to create new VLANs (from the Softlayer web ui).


/cc @denverwilliams @lixuna

**Comment by albee-jhoney** [comment]
All accounts may not have permissions to create vlans...
You have to either get permission from master-user of your account or raise a Softlayer ticket to get the vlan created, with names "public" and "private". 
https://console.bluemix.net/docs/infrastructure/vlans/getting-started.html

**Comment by brahmaroutu** [comment]
@Taylor @lixuna @denverwilliams Any updates on this? Please help debug the issue ASAP.

**Comment by kitch** [comment]
@taylor yeah, if you create a vm via the web ui, it will dynamically create new VLANs. The trick is if there is a situation where there are no VMs on a VLAN for more than a day or two, that VLAN will be garbage collected. FWIW, in IKS there is the option to create a new cluster with no VLANs specified, but this only works in the case where there are no existing VLANs. I'm not sure if the IKS terraform provider has this as an option. If so, you could catch the no vlan exception and then run the deploy with no vlans so that IKS/IBM Cloud will generate them for you automatically.

**Comment by albee-jhoney** [comment]
@taylor even in the IKS cluster resource (of the IBM Cloud terraform provider) the vlan-ids are optional (refer: https://ibm-cloud.github.io/tf-ibm-docs/v0.12.0/r/container_cluster.html).  

You can try to create the cluster, without providing the vlan-id (public & private).

cc: @hkantare @Praveengostu

**Comment by brahmaroutu** [comment]
@taylor @lixuna @denverwilliams can someone please look at this issue and see how we can help resolve.

**Comment by taylor** [comment]
@brahmaroutu, @albee-jhoney @kitch the missing VLAN issue is resolved.  After deploying a k8s cluster via the web ui the VLANs were created.

The k8s timeout seen (as of 20181113) is a new issue that seems to be coming from a new quota on the max number of k8s worker nodes which can be deployed.   See new ticket #81.

**Comment by brahmaroutu** [comment]
@Taylor Firstly, thanks for getting this done. This issue has been closed but the builds still show failing, can you please let me know if it takes a while for the successful build to finish?

**Comment by lixuna** [comment]
@brahmaroutu please see new cause of provisioning failures in https://github.com/crosscloudci/crosscloudci/issues/81

**Comment by brahmaroutu** [comment]
thanks @lixuna I should have read that above.
